/* ==========================================
   dic-ps.js – Dictionary for Price Simulator
   Author: Ken Okamoto
   Last updated: 2025-07-05
   ========================================== */
var dictionary = {
  ja: {
    // Meta / Global
    "page_title": "Keyvox - ようこそ！最適なプランで始めましょう",

    // Language Switcher
    "lang_ja": "日本語",
    "lang_en": "English",

    // Header Steps
    "steps_plan": "プラン設定",
    "steps_signup": "ログイン",
    "steps_account": "追加情報",
    "steps_confirm": "確認",
    "steps_complete": "完了",

    // Right Pane
    "right_pane_quote_text": "“リアルタイムデータにより、きめ細やかな運用と改善が可能に。もはやKEYVOXなしの運用は考えられません。”",
    "right_pane_quote_author": "鍵屋様",
    "right_pane_quote_author_title": "株式会社スマートフィットネス 代表取締役社長",
    "right_pane_features_title": "主な機能",
    "right_pane_feature_1": "低コスト導入でビジネスを加速: QR1 LEは電気工事不要で導入できます。",
    "right_pane_feature_2": "即時解錠オフラインQRコードで安全・快適なアクセス: ストレスフリーな体験を提供します。",
    "right_pane_feature_3": "リアルタイム履歴連携でビッグデータ管理に最適: 運用最適化や会員サービスの改善に貢献します。",
    "right_pane_trusted_by": "TRUSTED BY TEAMS AT",

    // Footer Buttons (Contextual)
    "button_back": "戻る",
    "button_next": "次へ進む",
    "button_complete_registration": "登録を完了する",
    "button_start_free_trial": "30日間無料トライアルを開始する",
    "button_go_to_dashboard": "管理画面にログインする",
    "button_send_auth_code": "認証コードを送信",
    "button_login": "ログイン",

    // Step 1: Plan Configuration
    "plan_base_price_info": "１アカウントあたり 2,500円（税込）",
    "plan_step1_title": "ステップ1: 利用形態とロック接続台数を選択",
    "plan_free_trial_badge": "30日間無料",
    "plan_service_keyvox_title": "KEYVOX通常サービスを利用",
    "plan_service_keyvox_desc": "全ての機能をご利用いただけます",
    "plan_service_keyvox_price": "¥2,500",
    "plan_price_unit": "/ 台・月 (税込)",
    "plan_service_api_title": "APIのみを利用",
    "plan_service_api_desc": "既存システムとの連携に",
    "plan_service_api_price": "¥1,650",
    "plan_lock_quantity": "ロック接続台数",
    "plan_step2_title": "ステップ2: 必要なパックを選択",
    "plan_pack_office_title": "オフィスパック",
    "plan_pack_price_prefix": "+ ",
    "plan_pack_office_price": "¥3,000",
    "plan_pack_price_suffix": "/月 (税込)",
    "plan_pack_office_feature_1": "管理ダッシュボード",
    "plan_pack_office_feature_2": "来客管理",
    "plan_pack_office_feature_3": "アクセス管理",
    "plan_pack_office_feature_4": "履歴管理",
    "plan_pack_office_feature_5": "ロックAPI",
    "plan_pack_hotel_title": "ホテルパック",
    "plan_pack_hotel_price": "¥5,000",
    "plan_pack_hotel_feature_1": "オフィスパックの全ての機能",
    "plan_pack_hotel_feature_2": "宿泊用PMS",
    "plan_pack_hotel_feature_3": "Webチェックイン",
    "plan_best_value_badge": "ベストバリュー",
    "plan_pack_business_title": "空間ビジネス最強パック",
    "plan_pack_business_price": "¥7,000",
    "plan_pack_business_feature_1": "ホテルパックの全ての機能",
    "plan_pack_business_feature_2": "サブスクリプション管理",
    "plan_pack_business_feature_3": "時間貸しPMS",
    "plan_pack_business_feature_4": "自社予約サイト",
    "plan_pack_business_feature_5": "予約API",
    "plan_trial_later_link": "30日無料でプランを後で決める",
    "plan_quantity_error": "台数を入力",
    "plan_footer_total": "合計月額料金（税込）",
    "ai_chat_button":"🚀 AIと相談する",
    "ai_chat_greeting": "🚀 こんにちは！何かお手伝いしますか？",
    "ai_chat_input_placeholder": "質問を入力...",
    "ai_chat_send_button": "送信",

    // Step 2: Login Information
    "login_subtitle": "新規登録、既にアカウントをお持ちのお客様。",
    "login_with_keyvox": "KEYVOX アカウントでログイン",
    "login_with_google": "Googleでログイン",
    "login_with_apple": "Appleでログイン",
    "login_no_account_prompt": "アカウントをお持ちでないですか？",
    "login_signup_link": "新規登録",
    "verify_recaptcha_label": "私はロボットではありません",
    "org_select_title": "ログインする組織を選択してください",
    "org_select_placeholder": "組織を選択...",
    "org_select_option_a": "組織A",
    "org_select_option_b": "組織B",
    "org_select_option_c": "組織C",
    "org_select_error": "組織を選択してください。",
    "org_select_cancel_button": "キャンセル",
    "org_select_login_button": "ログイン",

    // Step 3: Account Information
    "account_title": "追加情報",
    "account_subtitle": "追加で必要な情報をご入力ください。",
    "account_alert_required": "必須項目を入力してください。",
    "account_tab_signup": "新規登録",
    "account_tab_login": "ログイン",
    "account_form_company": "会社名",
    "account_form_name": "担当者名",
    "account_form_email": "メールアドレス",
    "account_form_facility": "ご利用施設名",
    "account_form_email_placeholder": "example@keyvox.co",
    "account_form_email_error": "メールアドレスの形式が正しくありません。",
    "account_form_phone": "携帯電話番号",
    "account_form_phone_placeholder": "09012345678",
    "account_or": "もしくは",

    // Step 4: Confirmation / Payment
    "payment_title": "お申し込み内容",
    "payment_company_name": "会社名",
    "payment_contact_name": "担当者名",
    "payment_email": "メールアドレス",
    "payment_phone": "携帯電話番号",
    "payment_plan": "プラン",
    "payment_lock_quantity": "ロック接続台数",
    "payment_total_monthly_fee": "合計月額料金（税込）",
    "payment_quote_link": "営業担当から個別のお見積りを入手されている場合はこちら",
    "payment_quote_number_label": "見積書番号",
    "payment_quote_number_placeholder": "000000",
    "payment_card_info_title": "カード情報",
    "payment_card_name_label": "カード名義人",
    "payment_card_name_placeholder": "TARO YAMADA",
    "payment_card_expiry_label": "有効期限",
    "payment_card_expiry_month": "MM",
    "payment_card_expiry_year": "YYYY",
    "payment_card_number_label": "カード番号",
    "payment_card_number_placeholder": "0000 0000 0000 0000",
    "payment_card_cvc_label": "CVC",
    "payment_card_cvc_placeholder": "CVC",
    "payment_bank_transfer_checkbox": "銀行振込をご希望の場合（法人のお客様）",

    // Step 4'1: Trial Confirmation
    "trial_confirm_title": "お申し込み内容",
    "trial_confirm_plan_label": "プラン",
    "trial_confirm_plan_value": "30日間無料トライアル",
    "trial_confirm_selected_plan_label": "選択中のプラン",
    "trial_confirm_selected_plan_value": "プランは後で選択",
    "trial_confirm_payment_label": "お支払い金額",
    "trial_confirm_terms": "30日以内に有料プランのご購入が必要です。ご購入がない場合は自動で解約され、データは削除されます。この処置は不可逆で、ご依頼を頂いても戻すことができません。",
    "trial_confirm_agree_checkbox": "注意事項に同意する",

    // Step 5: Complete
    "complete_title": "ご登録ありがとうございます！",
    "complete_subtitle": "アカウントの登録が完了しました。",
    "complete_email_notice": "ご登録のメールアドレスにも完了通知をお送りしております。",

    // Verification Modal
    "verify_modal_title": "ご登録のメールアドレス宛に<br>6桁の認証コードを送信しました。",
    "verify_modal_resend_link": "認証コードを再送信する",
    "verify_modal_resend_success": "認証コードを再送信しました。",
    "verify_modal_back_button": "アカウント情報入力に戻る",
    "verify_modal_next_button": "認証して次へ",

    // Password Reset Modal
    "pw_reset_modal_title": "パスワードを再設定する",
    "pw_reset_success_sent": "認証コードを送信しました。",
    "pw_reset_success_reset": "パスワードの再設定を行いました。",
    "pw_reset_error_mismatch": "パスワードが一致しません。",
    "pw_reset_phone_label": "携帯電話番号",
    "pw_reset_phone_country_jp": "+81 日本",
    "pw_reset_phone_country_us": "+1 米国",
    "pw_reset_phone_country_uk": "+44 英国",
    "pw_reset_phone_hint": "※ 頭の0を含むハイフンなしで入力してください。",
    "pw_reset_recaptcha": "I'm not a robot",
    "pw_reset_code_label": "認証コード",
    "pw_reset_code_placeholder": "認証コードを入力",
    "pw_reset_send_code_button": "コードを送信",
    "pw_reset_new_password_label": "新しいパスワード",
    "pw_reset_new_password_placeholder": "6桁以上のパスワードを設定",
    "pw_reset_new_password_confirm_label": "新しいパスワード (再入力)",
    "pw_reset_new_password_confirm_placeholder": "パスワードを再度入力",
    "pw_reset_submit_button": "パスワードを再設定する",
    "pw_reset_success_final_title": "パスワードがリセットされました",
    "pw_reset_success_final_subtitle": "ログイン画面に戻ります。",
    "pw_reset_success_final_close_button": "閉じる",

    // Bank Transfer Modal
    "bank_modal_title": "銀行振込に関する注意事項",
    "bank_modal_desc": "このオプションを選択した場合、KEYVOX担当部署での承認が必要となり、本ステップの登録を完了した後も直ぐにはご利用いただけません。",
    "bank_modal_rule1": "月額10万円未満の銀行払いは受け付けておりません。",
    "bank_modal_rule2": "まだ営業担当と会話をしていない場合は、先ずはご面談からとなります。",
    "bank_modal_alt_option": "直ぐにご利用を開始されたい場合は、クレジットカードをご選択ください。",
    "bank_modal_confirm_button": "上記を承知して登録に進む",
    "bank_modal_cancel_button": "クレジットカードを選択する",
  },
  en: {
    // Meta / Global
    "page_title": "Keyvox - Welcome! Let's Get Started with the Right Plan",
    
    // Language Switcher
    "lang_ja": "日本語",
    "lang_en": "English",

    // Header Steps
    "steps_plan": "Plan",
    "steps_signup": "Sign up",
    "steps_account": "Account Info",
    "steps_confirm": "Confirm",
    "steps_complete": "Complete",

    // Right Pane
    "right_pane_quote_text": "“Real-time data enables detailed operations and improvements. We can no longer imagine operating without KEYVOX.”",
    "right_pane_quote_author": "Mr. Kagiya",
    "right_pane_quote_author_title": "CEO, Smart Fitness Inc.",
    "right_pane_features_title": "Main Features",
    "right_pane_feature_1": "Accelerate your business with low-cost implementation: QR1 LE can be installed without electrical work.",
    "right_pane_feature_2": "Safe and convenient access with instant-unlock offline QR codes: Providing a stress-free experience.",
    "right_pane_feature_3": "Ideal for big data management with real-time history integration: Contributes to operational optimization and service improvement.",
    "right_pane_trusted_by": "TRUSTED BY TEAMS AT",

    // Footer Buttons (Contextual)
    "button_back": "Back",
    "button_next": "Next Step",
    "button_complete_registration": "Complete Registration",
    "button_start_free_trial": "Start 30-Day Free Trial",
    "button_go_to_dashboard": "Login to Dashboard",
    "button_send_auth_code": "Send Verification Code",
    "button_login": "Login",

    // Step 1: Plan Configuration
    "plan_base_price_info": "¥2,500 per account (tax included)",
    "plan_step1_title": "Step 1: Select Service Type and Number of Locks",
    "plan_free_trial_badge": "30-Day Free Trial",
    "plan_service_keyvox_title": "Use KEYVOX Standard Service",
    "plan_service_keyvox_desc": "Access all features.",
    "plan_service_keyvox_price": "¥2,500",
    "plan_price_unit": "/ lock / month (incl. tax)",
    "plan_service_api_title": "Use API Only",
    "plan_service_api_desc": "For integration with existing systems.",
    "plan_service_api_price": "¥1,650",
    "plan_lock_quantity": "Number of Locks",
    "plan_step2_title": "Step 2: Select Required Packs",
    "plan_pack_office_title": "Office Pack",
    "plan_pack_price_prefix": "+ ",
    "plan_pack_office_price": "¥3,000",
    "plan_pack_price_suffix": "/month (incl. tax)",
    "plan_pack_office_feature_1": "Admin Dashboard",
    "plan_pack_office_feature_2": "Visitor Management",
    "plan_pack_office_feature_3": "Access Management",
    "plan_pack_office_feature_4": "History Management",
    "plan_pack_office_feature_5": "Lock API",
    "plan_pack_hotel_title": "Hotel Pack",
    "plan_pack_hotel_price": "¥5,000",
    "plan_pack_hotel_feature_1": "All features of the Office Pack",
    "plan_pack_hotel_feature_2": "PMS for Hotels",
    "plan_pack_hotel_feature_3": "Web Check-in",
    "plan_best_value_badge": "Best Value",
    "plan_pack_business_title": "Ultimate Space Business Pack",
    "plan_pack_business_price": "¥7,000",
    "plan_pack_business_feature_1": "All features of the Hotel Pack",
    "plan_pack_business_feature_2": "Subscription Management",
    "plan_pack_business_feature_3": "Hourly Rental PMS",
    "plan_pack_business_feature_4": "Private Booking Site",
    "plan_pack_business_feature_5": "Booking API",
    "plan_trial_later_link": "Decide on a plan later with a 30-day free trial",
    "plan_quantity_error": "Enter quantity",
    "plan_footer_total": "Total Monthly Fee (incl. tax)",
    "ai_chat_button":"🚀 Ask AI",
    "ai_chat_greeting": "🚀 How can I help you?",
    "ai_chat_input_placeholder": "Type your question...",
    "ai_chat_send_button": "Send",

   // Step 3: Account Information
    "login_subtitle": "Sign up or login.",
    "login_with_keyvox": "Login with KEYVOX Account",
    "login_with_google": "Login with Google",
    "login_with_apple": "Login with Apple",
    "login_no_account_prompt": "Don't have an account?",
    "login_signup_link": "Sign up",
    "verify_recaptcha_label": "I'm not a robot",
    "org_select_title": "Please select an organization to log in",
    "org_select_placeholder": "Select an organization...",
    "org_select_option_a": "Organization A",
    "org_select_option_b": "Organization B",
    "org_select_option_c": "Organization C",
    "org_select_error": "Please select an organization.",
    "org_select_cancel_button": "Cancel",
    "org_select_login_button": "Login",

    // Step 3: Account Information
    "account_title": "Account Information",
    "account_subtitle": "Fill out additional information.",
    "account_alert_required": "Please fill in all required fields.",
    "account_tab_signup": "Sign Up",
    "account_tab_login": "Login",
    "account_form_company": "Company Name",
    "account_form_company_optional": "(Optional)",
    "account_form_name": "Contact Person's Name",
    "account_form_email": "Email Address",
    "account_form_email_placeholder": "example@keyvox.co",
    "account_form_email_error": "The email format is incorrect.",
    "account_form_facility": "Facility Name",
    "account_or": "or",

    // Step 4: Confirmation / Payment
    "payment_title": "Application Details",
    "payment_company_name": "Company Name",
    "payment_contact_name": "Contact Name",
    "payment_email": "Email Address",
    "payment_phone": "Phone Number",
    "payment_plan": "Plan",
    "payment_lock_quantity": "Number of Locks",
    "payment_total_monthly_fee": "Total Monthly Fee (incl. tax)",
    "payment_quote_link": "Click here if you have a custom quote from a sales representative",
    "payment_quote_number_label": "Quote Number",
    "payment_quote_number_placeholder": "000000",
    "payment_card_info_title": "Card Information",
    "payment_card_name_label": "Name on Card",
    "payment_card_name_placeholder": "TARO YAMADA",
    "payment_card_expiry_label": "Expiration Date",
    "payment_card_expiry_month": "MM",
    "payment_card_expiry_year": "YYYY",
    "payment_card_number_label": "Card Number",
    "payment_card_number_placeholder": "0000 0000 0000 0000",
    "payment_card_cvc_label": "CVC",
    "payment_card_cvc_placeholder": "CVC",
    "payment_bank_transfer_checkbox": "For bank transfer requests (corporate customers only)",

    // Step 4': Trial Confirmation
    "trial_confirm_title": "Application Details",
    "trial_confirm_plan_label": "Plan",
    "trial_confirm_plan_value": "30-Day Free Trial",
    "trial_confirm_selected_plan_label": "Selected Plan",
    "trial_confirm_selected_plan_value": "To be selected later",
    "trial_confirm_payment_label": "Amount to be paid",
    "trial_confirm_terms": "A paid plan must be purchased within 30 days. Otherwise, the account will be automatically canceled and the data will be deleted. This action is irreversible and cannot be undone upon request.",
    "trial_confirm_agree_checkbox": "I agree to the terms and conditions",

    // Step 5: Complete
    "complete_title": "Thank you for registering!",
    "complete_subtitle": "Your account has been successfully created.",
    "complete_email_notice": "A confirmation notice has also been sent to your registered email address.",

    // Verification Modal
    "verify_modal_title": "A 6-digit verification code has been sent to your registered email address.",
    "verify_modal_resend_link": "Resend verification code",
    "verify_modal_resend_success": "Verification code resent.",
    "verify_modal_back_button": "Back to Account Information",
    "verify_modal_next_button": "Verify and Continue",

    // Password Reset Modal
    "pw_reset_modal_title": "Reset Password",
    "pw_reset_success_sent": "Verification code sent.",
    "pw_reset_success_reset": "Password has been reset.",
    "pw_reset_error_mismatch": "The new passwords do not match.",
    "pw_reset_phone_label": "Mobile Phone Number",
    "pw_reset_phone_country_jp": "+81 Japan",
    "pw_reset_phone_country_us": "+1 US",
    "pw_reset_phone_country_uk": "+44 UK",
    "pw_reset_phone_hint": "* Please enter without hyphens, including the initial 0.",
    "pw_reset_recaptcha": "I'm not a robot",
    "pw_reset_code_label": "Verification Code",
    "pw_reset_code_placeholder": "Enter verification code",
    "pw_reset_send_code_button": "Send Code",
    "pw_reset_new_password_label": "New Password",
    "pw_reset_new_password_placeholder": "Set a password of at least 6 digits",
    "pw_reset_new_password_confirm_label": "New Password (Re-enter)",
    "pw_reset_new_password_confirm_placeholder": "Re-enter password",
    "pw_reset_submit_button": "Reset Password",
    "pw_reset_success_final_title": "Password has been reset",
    "pw_reset_success_final_subtitle": "Returning to the login screen.",
    "pw_reset_success_final_close_button": "Close",

    // Bank Transfer Modal
    "bank_modal_title": "Important Notes on Bank Transfers",
    "bank_modal_desc": "If you choose this option, approval from the KEYVOX department is required, and you will not be able to use the service immediately after completing this registration step.",
    "bank_modal_rule1": "Bank transfers for amounts less than 100,000 JPY per month are not accepted.",
    "bank_modal_rule2": "If you have not yet spoken with a sales representative, an initial meeting will be required.",
    "bank_modal_alt_option": "If you wish to start using the service immediately, please select credit card.",
    "bank_modal_confirm_button": "I understand and wish to proceed",
    "bank_modal_cancel_button": "Select Credit Card",
  }
};
